"""Rename legacy_id to old_system_id without index

Revision ID: 18d9f168a2eb
Revises: 2e65696db9ba
Create Date: 2026-04-21 09:37:04.414382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d9f168a2eb'
down_revision: Union[str, Sequence[str], None] = '2e65696db9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_cards_legacy_id'), table_name='cards')
    op.alter_column('classes', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_classes_legacy_id'), table_name='classes')
    op.alter_column('lessons', 'legacy_id', new_column_name='old_system_id')
    op.alter_column('lessons', 'legacy_subject_id', new_column_name='old_system_subject_id')
    op.alter_column('lessons', 'legacy_teacher_id', new_column_name='old_system_teacher_id')
    op.alter_column('lessons', 'legacy_class_id', new_column_name='old_system_class_id')
    op.drop_index(op.f('ix_lessons_legacy_id'), table_name='lessons')
    op.alter_column('observations', 'legacy_id', new_column_name='old_system_id')
    op.alter_column('observations', 'legacy_session_id', new_column_name='old_system_session_id')
    op.alter_column('observations', 'legacy_teacher_id', new_column_name='old_system_teacher_id')
    op.drop_index(op.f('ix_observations_legacy_id'), table_name='observations')
    op.alter_column('permissions', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_permissions_legacy_id'), table_name='permissions')
    # op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.alter_column('roles', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_roles_legacy_id'), table_name='roles')
    op.alter_column('rpt_planilla', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_rpt_planilla_legacy_id'), table_name='rpt_planilla')
    op.alter_column('schedule_sessions', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_schedule_sessions_legacy_id'), table_name='schedule_sessions')
    op.alter_column('teachers', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_teachers_legacy_id'), table_name='teachers')
    # op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.alter_column('users', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_users_legacy_id'), table_name='users')
    op.alter_column('xml_change_logs', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_xml_change_logs_legacy_id'), table_name='xml_change_logs')
    op.alter_column('xml_upload_logs', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_xml_upload_logs_legacy_id'), table_name='xml_upload_logs')
    op.alter_column('xml_uploads', 'legacy_id', new_column_name='old_system_id')
    op.drop_index(op.f('ix_xml_uploads_legacy_id'), table_name='xml_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xml_uploads', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_xml_uploads_legacy_id'), 'xml_uploads', ['legacy_id'], unique=False)
    op.alter_column('xml_upload_logs', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_xml_upload_logs_legacy_id'), 'xml_upload_logs', ['legacy_id'], unique=False)
    op.alter_column('xml_change_logs', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_xml_change_logs_legacy_id'), 'xml_change_logs', ['legacy_id'], unique=False)
    op.alter_column('users', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_users_legacy_id'), 'users', ['legacy_id'], unique=False)
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.alter_column('teachers', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_teachers_legacy_id'), 'teachers', ['legacy_id'], unique=False)
    op.alter_column('schedule_sessions', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_schedule_sessions_legacy_id'), 'schedule_sessions', ['legacy_id'], unique=False)
    op.alter_column('rpt_planilla', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_rpt_planilla_legacy_id'), 'rpt_planilla', ['legacy_id'], unique=False)
    op.alter_column('roles', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_roles_legacy_id'), 'roles', ['legacy_id'], unique=False)
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.alter_column('permissions', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_permissions_legacy_id'), 'permissions', ['legacy_id'], unique=False)
    op.alter_column('observations', 'old_system_teacher_id', new_column_name='legacy_teacher_id')
    op.alter_column('observations', 'old_system_id', new_column_name='legacy_id')
    op.alter_column('observations', 'old_system_session_id', new_column_name='legacy_session_id')
    op.create_index(op.f('ix_observations_legacy_id'), 'observations', ['legacy_id'], unique=False)
    op.alter_column('lessons', 'old_system_teacher_id', new_column_name='legacy_teacher_id')
    op.alter_column('lessons', 'old_system_id', new_column_name='legacy_id')
    op.alter_column('lessons', 'old_system_class_id', new_column_name='legacy_class_id')
    op.alter_column('lessons', 'old_system_subject_id', new_column_name='legacy_subject_id')
    op.create_index(op.f('ix_lessons_legacy_id'), 'lessons', ['legacy_id'], unique=False)
    op.alter_column('classes', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_classes_legacy_id'), 'classes', ['legacy_id'], unique=False)
    op.alter_column('cards', 'old_system_id', new_column_name='legacy_id')
    op.create_index(op.f('ix_cards_legacy_id'), 'cards', ['legacy_id'], unique=False)
    # ### end Alembic commands ###
