"""baseline_v2_uuid

Revision ID: 2e65696db9ba
Revises: 
Create Date: 2026-04-16 12:25:00.538587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e65696db9ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('grades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lunch_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_legacy_id'), 'permissions', ['legacy_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_legacy_id'), 'roles', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('rpt_planilla',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('fecha_clase', sa.Date(), nullable=False),
    sa.Column('docente', sa.String(length=255), nullable=False),
    sa.Column('horas_dictadas', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpt_planilla_docente'), 'rpt_planilla', ['docente'], unique=False)
    op.create_index(op.f('ix_rpt_planilla_fecha_clase'), 'rpt_planilla', ['fecha_clase'], unique=False)
    op.create_index(op.f('ix_rpt_planilla_legacy_id'), 'rpt_planilla', ['legacy_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('dni', sa.String(length=15), nullable=True),
    sa.Column('normalized_name', sa.String(length=400), nullable=True),
    sa.Column('possible_duplicate', sa.Boolean(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.Column('times_detected', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('possible_match_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['possible_match_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_teachers_is_assigned'), 'teachers', ['is_assigned'], unique=False)
    op.create_index(op.f('ix_teachers_legacy_id'), 'teachers', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_teachers_normalized_name'), 'teachers', ['normalized_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_legacy_id'), 'users', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('xml_uploads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xml_uploads_legacy_id'), 'xml_uploads', ['legacy_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_classes_legacy_id'), 'classes', ['legacy_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('xml_change_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['xml_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xml_change_logs_legacy_id'), 'xml_change_logs', ['legacy_id'], unique=False)
    op.create_table('xml_upload_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['xml_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xml_upload_logs_legacy_id'), 'xml_upload_logs', ['legacy_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('legacy_subject_id', sa.Integer(), nullable=True),
    sa.Column('legacy_teacher_id', sa.Integer(), nullable=True),
    sa.Column('legacy_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_lessons_legacy_id'), 'lessons', ['legacy_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('days', sa.String(length=10), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_cards_legacy_id'), 'cards', ['legacy_id'], unique=False)
    op.create_table('schedule_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_sessions_legacy_id'), 'schedule_sessions', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_schedule_sessions_session_date'), 'schedule_sessions', ['session_date'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('replacement_teacher_id', sa.UUID(), nullable=True),
    sa.Column('legacy_session_id', sa.Integer(), nullable=True),
    sa.Column('legacy_teacher_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('replacement_teacher_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['replacement_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['schedule_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_legacy_id'), 'observations', ['legacy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_legacy_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_schedule_sessions_session_date'), table_name='schedule_sessions')
    op.drop_index(op.f('ix_schedule_sessions_legacy_id'), table_name='schedule_sessions')
    op.drop_table('schedule_sessions')
    op.drop_index(op.f('ix_cards_legacy_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_lessons_legacy_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_xml_upload_logs_legacy_id'), table_name='xml_upload_logs')
    op.drop_table('xml_upload_logs')
    op.drop_index(op.f('ix_xml_change_logs_legacy_id'), table_name='xml_change_logs')
    op.drop_table('xml_change_logs')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_classes_legacy_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_xml_uploads_legacy_id'), table_name='xml_uploads')
    op.drop_table('xml_uploads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_legacy_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_normalized_name'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_legacy_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_is_assigned'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_rpt_planilla_legacy_id'), table_name='rpt_planilla')
    op.drop_index(op.f('ix_rpt_planilla_fecha_clase'), table_name='rpt_planilla')
    op.drop_index(op.f('ix_rpt_planilla_docente'), table_name='rpt_planilla')
    op.drop_table('rpt_planilla')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_legacy_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_legacy_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('lunch_config')
    op.drop_table('grades')
    op.drop_table('buildings')
    op.drop_table('break_config')
    # ### end Alembic commands ###
