"""test

Revision ID: af4a3c64494c
Revises: 0529fb697cac
Create Date: 2026-04-23 14:32:01.349852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4a3c64494c'
down_revision: Union[str, Sequence[str], None] = '0529fb697cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('cards', 'old_system_id')
    op.add_column('classes', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('classes', 'old_system_id')
    op.add_column('lessons', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('lessons', 'old_system_id')
    op.add_column('observations', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('observations', 'old_system_id')
    op.add_column('permissions', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('permissions', 'old_system_id')
    # op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.add_column('roles', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('roles', 'old_system_id')
    op.add_column('rpt_planilla', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('rpt_planilla', 'old_system_id')
    op.add_column('schedule_sessions', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('schedule_sessions', 'old_system_id')
    op.add_column('teachers', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teachers_normalized_for_match'), 'teachers', ['normalized_for_match'], unique=False)
    op.drop_column('teachers', 'old_system_id')
    # op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.add_column('users', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'old_system_id')
    op.add_column('xml_change_logs', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('xml_change_logs', 'old_system_id')
    op.add_column('xml_upload_logs', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('xml_upload_logs', 'old_system_id')
    op.add_column('xml_uploads', sa.Column('legacy_id', sa.Integer(), nullable=True))
    op.drop_column('xml_uploads', 'old_system_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_uploads', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('xml_uploads', 'legacy_id')
    op.add_column('xml_upload_logs', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('xml_upload_logs', 'legacy_id')
    op.add_column('xml_change_logs', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('xml_change_logs', 'legacy_id')
    op.add_column('users', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'legacy_id')
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.add_column('teachers', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_teachers_normalized_for_match'), table_name='teachers')
    op.drop_column('teachers', 'legacy_id')
    op.add_column('schedule_sessions', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('schedule_sessions', 'legacy_id')
    op.add_column('rpt_planilla', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rpt_planilla', 'legacy_id')
    op.add_column('roles', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('roles', 'legacy_id')
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.add_column('permissions', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('permissions', 'legacy_id')
    op.add_column('observations', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('observations', 'legacy_id')
    op.add_column('lessons', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'legacy_id')
    op.add_column('classes', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('classes', 'legacy_id')
    op.add_column('cards', sa.Column('old_system_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'legacy_id')
    # ### end Alembic commands ###
