"""standardize_legacy_naming_v3

Revision ID: cdfde098f7a4
Revises: af4a3c64494c
Create Date: 2026-04-24 13:02:05.594521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdfde098f7a4'
down_revision: Union[str, Sequence[str], None] = 'af4a3c64494c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_legacy_id'), table_name='cards')
    op.drop_index(op.f('ix_classes_legacy_id'), table_name='classes')
    op.drop_index(op.f('ix_lessons_legacy_id'), table_name='lessons')
    op.create_index(op.f('ix_lessons_legacy_class_id'), 'lessons', ['legacy_class_id'], unique=False)
    op.create_index(op.f('ix_lessons_legacy_subject_id'), 'lessons', ['legacy_subject_id'], unique=False)
    op.create_index(op.f('ix_lessons_legacy_teacher_id'), 'lessons', ['legacy_teacher_id'], unique=False)
    op.drop_index(op.f('ix_observations_legacy_id'), table_name='observations')
    op.create_index(op.f('ix_observations_legacy_session_id'), 'observations', ['legacy_session_id'], unique=False)
    op.create_index(op.f('ix_observations_legacy_teacher_id'), 'observations', ['legacy_teacher_id'], unique=False)
    op.drop_index(op.f('ix_permissions_legacy_id'), table_name='permissions')
    op.create_unique_constraint('uq_role_permission', 'role_permissions', ['role_id', 'permission_id'])
    op.drop_index(op.f('ix_roles_legacy_id'), table_name='roles')
    op.drop_index(op.f('ix_rpt_planilla_legacy_id'), table_name='rpt_planilla')
    op.drop_index(op.f('ix_schedule_sessions_legacy_id'), table_name='schedule_sessions')
    op.drop_index(op.f('ix_teachers_legacy_id'), table_name='teachers')
    op.create_unique_constraint('uq_user_role', 'user_roles', ['user_id', 'role_id'])
    op.drop_index(op.f('ix_users_legacy_id'), table_name='users')
    op.drop_index(op.f('ix_xml_change_logs_legacy_id'), table_name='xml_change_logs')
    op.drop_index(op.f('ix_xml_upload_logs_legacy_id'), table_name='xml_upload_logs')
    op.drop_index(op.f('ix_xml_uploads_legacy_id'), table_name='xml_uploads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_xml_uploads_legacy_id'), 'xml_uploads', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_xml_upload_logs_legacy_id'), 'xml_upload_logs', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_xml_change_logs_legacy_id'), 'xml_change_logs', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_users_legacy_id'), 'users', ['legacy_id'], unique=False)
    op.drop_constraint('uq_user_role', 'user_roles', type_='unique')
    op.create_index(op.f('ix_teachers_legacy_id'), 'teachers', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_schedule_sessions_legacy_id'), 'schedule_sessions', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_rpt_planilla_legacy_id'), 'rpt_planilla', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_roles_legacy_id'), 'roles', ['legacy_id'], unique=False)
    op.drop_constraint('uq_role_permission', 'role_permissions', type_='unique')
    op.create_index(op.f('ix_permissions_legacy_id'), 'permissions', ['legacy_id'], unique=False)
    op.drop_index(op.f('ix_observations_legacy_teacher_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_legacy_session_id'), table_name='observations')
    op.create_index(op.f('ix_observations_legacy_id'), 'observations', ['legacy_id'], unique=False)
    op.drop_index(op.f('ix_lessons_legacy_teacher_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_legacy_subject_id'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_legacy_class_id'), table_name='lessons')
    op.create_index(op.f('ix_lessons_legacy_id'), 'lessons', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_classes_legacy_id'), 'classes', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_cards_legacy_id'), 'cards', ['legacy_id'], unique=False)
    # ### end Alembic commands ###
